services:
  postgres:
    image: postgres:16-alpine
    container_name: employee-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ./docker/postgres/02-blue-schema.sql:/docker-entrypoint-initdb.d/02-blue-schema.sql:ro
      - ./docker/postgres/03-green-schema.sql:/docker-entrypoint-initdb.d/03-green-schema.sql:ro
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  backend-blue:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: employee-backend-blue
    restart: unless-stopped
    environment:
      PORT: 4001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: blue_user
      DB_PASSWORD: blue_password
      DB_NAME: threetierapp_blue
    ports:
      - "4001:4001"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  frontend-blue:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://13.234.232.171:4001
    container_name: employee-frontend-blue
    restart: unless-stopped
    ports:
      - "3001:80"
    depends_on:
      - backend-blue
    networks:
      - app-network

  backend-green:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: employee-backend-green
    restart: unless-stopped
    environment:
      PORT: 4002
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: green_user
      DB_PASSWORD: green_password
      DB_NAME: threetierapp_green
    ports:
      - "4002:4002"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  frontend-green:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://13.234.232.171:4002
    container_name: employee-frontend-green
    restart: unless-stopped
    ports:
      - "3002:80"
    depends_on:
      - backend-green
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: