server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Serve React application
    location / {
        try_files $uri /index.html;
    }

    # Forward API requests to the backend
    location /api/ {
        proxy_pass http://backend-green:4002/api/;
    }

    # Docker health check
    location /healthz {
        return 200 "OK";
    }
}